/**
 * Club Abbreviations Mapping
 * 
 * Centralized source of truth for club abbreviations used across the application.
 * These are standard 3-letter codes commonly used in football/soccer.
 */

export const CLUB_ABBREVIATIONS: Record<string, string> = {
    // English Premier League
    'arsenal': 'ARS',
    'aston-villa': 'AVL',
    'bournemouth': 'BOU',
    'afc-bournemouth': 'BOU',
    'brentford': 'BRE',
    'brighton-hove-albion': 'BHA',
    'brighton': 'BHA',
    'chelsea': 'CHE',
    'crystal-palace': 'CRY',
    'everton': 'EVE',
    'fulham': 'FUL',
    'liverpool': 'LIV',
    'luton-town': 'LUT',
    'manchester-city': 'MCI',
    'manchester-united': 'MUN',
    'newcastle-united': 'NEW',
    'nottingham-forest': 'NFO',
    'sheffield-united': 'SHU',
    'tottenham-hotspur': 'TOT',
    'tottenham': 'TOT',
    'spurs': 'TOT',
    'west-ham-united': 'WHU',
    'west-ham': 'WHU',
    'wolverhampton-wanderers': 'WOL',
    'wolves': 'WOL',
    'burnley': 'BUR',
    'leicester-city': 'LEI',
    'leeds-united': 'LEE',
    'southampton': 'SOU',
    'watford': 'WAT',
    'norwich-city': 'NOR',
    'ipswich-town': 'IPS',

    // Spanish La Liga
    'real-madrid': 'RMA',
    'barcelona': 'BAR',
    'fc-barcelona': 'BAR',
    'atletico-madrid': 'ATM',
    'sevilla': 'SEV',
    'sevilla-fc': 'SEV',
    'valencia': 'VAL',
    'valencia-cf': 'VAL',
    'villarreal': 'VIL',
    'villarreal-cf': 'VIL',
    'real-sociedad': 'RSO',
    'athletic-bilbao': 'ATH',
    'athletic-club': 'ATH',
    'real-betis': 'BET',
    'celta-vigo': 'CEL',
    'rc-celta': 'CEL',
    'espanyol': 'ESP',
    'getafe': 'GET',
    'getafe-cf': 'GET',
    'granada': 'GRA',
    'granada-cf': 'GRA',
    'levante': 'LEV',
    'mallorca': 'MLL',
    'rcd-mallorca': 'MLL',
    'osasuna': 'OSA',
    'rayo-vallecano': 'RAY',
    'real-valladolid': 'VLD',
    'girona': 'GIR',
    'girona-fc': 'GIR',
    'las-palmas': 'LPA',
    'ud-las-palmas': 'LPA',
    'alaves': 'ALA',
    'deportivo-alaves': 'ALA',
    'cadiz': 'CAD',
    'cadiz-cf': 'CAD',
    'almeria': 'ALM',
    'ud-almeria': 'ALM',

    // German Bundesliga
    'bayern-munich': 'FCB',
    'bayern-munchen': 'FCB',
    'fc-bayern-munich': 'FCB',
    'borussia-dortmund': 'BVB',
    'rb-leipzig': 'RBL',
    'bayer-leverkusen': 'B04',
    'bayer-04-leverkusen': 'B04',
    'union-berlin': 'FCU',
    'fc-union-berlin': 'FCU',
    'sc-freiburg': 'SCF',
    'freiburg': 'SCF',
    'eintracht-frankfurt': 'SGE',
    'vfl-wolfsburg': 'WOB',
    'wolfsburg': 'WOB',
    'borussia-monchengladbach': 'BMG',
    'borussia-mgladbach': 'BMG',
    'mainz-05': 'M05',
    'fsv-mainz-05': 'M05',
    'mainz': 'M05',
    'fc-koln': 'KOE',
    'koln': 'KOE',
    'cologne': 'KOE',
    'hoffenheim': 'HOF',
    'tsg-hoffenheim': 'HOF',
    'hertha-berlin': 'BSC',
    'hertha-bsc': 'BSC',
    'vfb-stuttgart': 'VFB',
    'stuttgart': 'VFB',
    'werder-bremen': 'SVW',
    'fc-augsburg': 'FCA',
    'augsburg': 'FCA',
    'vfl-bochum': 'BOC',
    'bochum': 'BOC',
    'arminia-bielefeld': 'DSC',
    'greuther-furth': 'SGF',
    'heidenheim': 'HDH',
    'fc-heidenheim': 'HDH',
    'st-pauli': 'STP',
    'fc-st-pauli': 'STP',
    'holstein-kiel': 'KIE',

    // Italian Serie A
    'juventus': 'JUV',
    'inter-milan': 'INT',
    'internazionale': 'INT',
    'inter': 'INT',
    'fc-internazionale-milano': 'INT',
    'ac-milan': 'MIL',
    'milan': 'MIL',
    'napoli': 'NAP',
    'ssc-napoli': 'NAP',
    'as-roma': 'ROM',
    'roma': 'ROM',
    'lazio': 'LAZ',
    'ss-lazio': 'LAZ',
    'atalanta': 'ATA',
    'fiorentina': 'FIO',
    'acf-fiorentina': 'FIO',
    'torino': 'TOR',
    'torino-fc': 'TOR',
    'sampdoria': 'SAM',
    'uc-sampdoria': 'SAM',
    'bologna': 'BOL',
    'bologna-fc': 'BOL',
    'sassuolo': 'SAS',
    'us-sassuolo': 'SAS',
    'udinese': 'UDI',
    'hellas-verona': 'VER',
    'verona': 'VER',
    'cagliari': 'CAG',
    'cagliari-calcio': 'CAG',
    'empoli': 'EMP',
    'empoli-fc': 'EMP',
    'genoa': 'GEN',
    'genoa-cfc': 'GEN',
    'lecce': 'LEC',
    'us-lecce': 'LEC',
    'monza': 'MON',
    'ac-monza': 'MON',
    'salernitana': 'SAL',
    'us-salernitana': 'SAL',
    'spezia': 'SPE',
    'spezia-calcio': 'SPE',
    'venezia': 'VEN',
    'venezia-fc': 'VEN',
    'frosinone': 'FRO',
    'frosinone-calcio': 'FRO',
    'parma': 'PAR',
    'parma-calcio': 'PAR',
    'como': 'COM',
    'como-1907': 'COM',

    // French Ligue 1
    'paris-saint-germain': 'PSG',
    'psg': 'PSG',
    'marseille': 'OM',
    'olympique-marseille': 'OM',
    'lyon': 'OL',
    'olympique-lyonnais': 'OL',
    'monaco': 'MON',
    'as-monaco': 'MON',
    'lille': 'LIL',
    'losc-lille': 'LIL',
    'rennes': 'REN',
    'stade-rennais': 'REN',
    'nice': 'NIC',
    'ogc-nice': 'NIC',
    'lens': 'RCL',
    'rc-lens': 'RCL',
    'montpellier': 'MON',
    'montpellier-hsc': 'MON',
    'strasbourg': 'STR',
    'rc-strasbourg': 'STR',
    'nantes': 'NAN',
    'fc-nantes': 'NAN',
    'reims': 'REI',
    'stade-reims': 'REI',
    'brest': 'BRE',
    'stade-brestois': 'BRE',
    'angers': 'ANG',
    'angers-sco': 'ANG',
    'lorient': 'LOR',
    'fc-lorient': 'LOR',
    'toulouse': 'TOU',
    'toulouse-fc': 'TOU',
    'clermont-foot': 'CF6',
    'clermont': 'CF6',
    'troyes': 'TRO',
    'estac-troyes': 'TRO',
    'auxerre': 'AUX',
    'aj-auxerre': 'AUX',
    'le-havre': 'HAC',
    'le-havre-ac': 'HAC',
    'metz': 'MET',
    'fc-metz': 'MET',
    'saint-etienne': 'STE',
    'as-saint-etienne': 'STE',

    // Other Notable European Clubs
    'ajax': 'AJA',
    'afc-ajax': 'AJA',
    'psv-eindhoven': 'PSV',
    'psv': 'PSV',
    'feyenoord': 'FEY',
    'benfica': 'BEN',
    'sl-benfica': 'BEN',
    'porto': 'POR',
    'fc-porto': 'POR',
    'sporting-cp': 'SCP',
    'sporting-lisbon': 'SCP',
    'sporting': 'SCP',
    'anderlecht': 'AND',
    'rsc-anderlecht': 'AND',
    'club-brugge': 'CLB',
    'celtic': 'CEL',
    'celtic-fc': 'CEL',
    'rangers': 'RAN',
    'rangers-fc': 'RAN',
    'galatasaray': 'GAL',
    'fenerbahce': 'FEN',
    'besiktas': 'BES',
    'shakhtar-donetsk': 'SHK',
    'dynamo-kyiv': 'DYN',
    'red-bull-salzburg': 'RBS',
    'fc-salzburg': 'RBS',
    'olympiacos': 'OLY',
    'panathinaikos': 'PAO',
    'crvena-zvezda': 'CZV',
    'red-star-belgrade': 'CZV',
    'dinamo-zagreb': 'DZG',
};

/**
 * Get club abbreviation by slug
 * Falls back to first 3 uppercase characters of title if not found
 */
export function getClubAbbreviation(slug: string, title?: string): string {
    const normalized = slug?.toLowerCase().trim();

    if (CLUB_ABBREVIATIONS[normalized]) {
        return CLUB_ABBREVIATIONS[normalized];
    }

    // Fallback: first 3 chars of title in uppercase
    if (title) {
        return title.substring(0, 3).toUpperCase();
    }

    // Last resort: first 3 chars of slug
    return slug?.substring(0, 3).toUpperCase() || 'CLB';
}
